<a href="https://colab.research.google.com/github/vegaangga/Prediksi-Beasiswa-Menggunakan-KNN/blob/main/Machine_Learning_Prediksi_Beasiswa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Classification with KNN

In [ ]:
## Kelulusan student exchange
import numpy as np

X_train = np.array([
    [2.75, 3.05, 2.65, 375, 0.6, 0],
    [4, 3.8,3.9,360,1,1],
    [3, 3.35, 3.15, 395, 0.85,1],
    [2.05, 3, 2.75, 350, 0.5,0],
    [2.95, 3.5, 3, 365, 0.5,1],
    [3.5, 3, 3.35, 420, 0.75,0],
    [3.25, 2.8, 3, 355, 0.8,1],
    [4, 3.5, 3.75,400,0.95,1],
    [2.5, 3, 3.25, 450,1,1],
    [3.75, 3, 3.6, 351, 0.85,0]
])

y_train = ['lulus',
           'tidak',
           'lulus',
           'tidak',
           'tidak',
           'lulus',
           'tidak', 
           'lulus',
           'lulus',
           'tidak']

In [ ]:
## meghitung data uji 1
x = np.array([[3.65, 3.8,3.75,380,1,0]])

distances = np.sqrt(np.sum((X_train - x)**2, axis=1))
distances

array([ 5.26711496, 20.02860454, 15.06676807, 30.07407521, 15.07953912,
       40.01106097, 25.05518908, 20.03035197, 70.02294267, 29.01198028])

In [ ]:
# hitung tentangga k=3
nearest_neighbor_indices = distances.argsort()[:3]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['lulus', 'lulus', 'tidak'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:3]))
b.most_common(1)[0][0]

'lulus'

In [ ]:
# hitung tentangga k=5
nearest_neighbor_indices = distances.argsort()[:5]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['lulus', 'lulus', 'tidak', 'tidak', 'lulus'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:5]))
b.most_common(1)[0][0]

'lulus'

Data Uji 2

In [ ]:
## meghitung jarak euclidean data uji 2
x = np.array([[2.4, 2.15,2.25,300,0.55,0]])

distances = np.sqrt(np.sum((X_train - x)**2, axis=1))
distances

array([ 75.00729964,  60.07668017,  95.01947169,  50.0109738 ,
        65.02837842, 120.01325968,  55.02517606, 100.03895491,
       150.00978301,  51.04368227])

In [ ]:
# mengurutkan jarak secara ascending k=3
nearest_neighbor_indices = distances.argsort()[:3]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['tidak', 'tidak', 'tidak'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:3]))
b.most_common(1)[0][0]

'tidak'

In [ ]:
# hitung tentangga k=5
nearest_neighbor_indices = distances.argsort()[:5]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['tidak', 'tidak', 'tidak', 'tidak', 'tidak'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:5]))
b.most_common(1)[0][0]

'tidak'

Data Uji 3

In [ ]:
## meghitung data uji 3
x = np.array([[3.85, 3.65,3.9,380,0.7,1]])

distances = np.sqrt(np.sum((X_train - x)**2, axis=1))
distances

array([ 5.39837939, 20.00337472, 15.04651122, 30.10024917, 15.05597888,
       40.02311832, 25.03802109, 20.00324974, 70.01969366, 29.02662571])

In [ ]:
# hitung tentangga k=3
nearest_neighbor_indices = distances.argsort()[:3]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['lulus', 'lulus', 'tidak'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:3]))
b.most_common(1)[0][0]

'lulus'

In [ ]:
# hitung tentangga k=5
nearest_neighbor_indices = distances.argsort()[:5]
nearest_neighbor_genders = np.take(y_train, nearest_neighbor_indices)
nearest_neighbor_genders

array(['lulus', 'lulus', 'tidak', 'lulus', 'tidak'], dtype='<U5')

In [ ]:
## ambil dominan
from collections import Counter
b = Counter(np.take(y_train, distances.argsort()[:5]))
b.most_common(1)[0][0]

'lulus'

Menghitung akurasi

In [ ]:
## Contoh 5
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([
    [2.75, 3.05, 2.65, 375, 0.6, 0],
    [4, 3.8,3.9,360,1,1],
    [3, 3.35, 3.15, 395, 0.85,1],
    [2.05, 3, 2.75, 350, 0.5,0],
    [2.95, 3.5, 3, 365, 0.5,1],
    [3.5, 3, 3.35, 420, 0.75,0],
    [3.25, 2.8, 3, 355, 0.8,1],
    [4, 3.5, 3.75,400,0.95,1],
    [2.5, 3, 3.25, 450,1,1],
    [3.75, 3, 3.6, 351, 0.85,0]
])

y_train = ['lulus',
           'tidak',
           'lulus',
           'tidak',
           'tidak',
           'lulus',
           'tidak', 
           'lulus',
           'lulus',
           'tidak']


In [ ]:
## Contoh 6
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_train_binarized = lb.fit_transform(y_train)
y_train_binarized

array([[0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [ ]:
K = 3
clf = KNeighborsClassifier(n_neighbors=K)
clf.fit(X_train, y_train_binarized.reshape(-1))
prediction_binarized = clf.predict(np.array([3.65, 3.8,3.75,380,1]).reshape(1, -1))[0]
predicted_label = lb.inverse_transform(prediction_binarized)
predicted_label

array(['lulus'], dtype='<U5')

In [ ]:
X_test = np.array([
    [3.65, 3.8,3.75,380,1],
    [2.4, 2.15,2.25,300,0.55],
    [3.85, 3.65,3.9,380,0.7],
])
y_test = ['lulus', 'tidak', 'tidak']
y_test_binarized = lb.transform(y_test)
print('Binarized labels: %s' % y_test_binarized.T[0])

predictions_binarized = clf.predict(X_test)
print('Binarized predictions: %s' % predictions_binarized)
print('Predicted labels: %s' % lb.inverse_transform(predictions_binarized))

Binarized labels: [0 1 1]
Binarized predictions: [0 1 0]
Predicted labels: ['lulus' 'tidak' 'lulus']


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %s' % accuracy_score(y_test_binarized, predictions_binarized))

Accuracy: 0.6666666666666666


In [ ]:
from sklearn.metrics import precision_score
print('Precision: %s' % precision_score(y_test_binarized, predictions_binarized))

Precision: 1.0


In [ ]:
from sklearn.metrics import recall_score
print('Recall: %s' % recall_score(y_test_binarized, predictions_binarized))

Recall: 0.5


In [ ]:
from sklearn.metrics import f1_score
print('F1 score: %s' % f1_score(y_test_binarized, predictions_binarized))


F1 score: 0.6666666666666666


In [ ]:
from sklearn.metrics import matthews_corrcoef
print('Matthews correlation coefficient: %s' % matthews_corrcoef(y_test_binarized, predictions_binarized))

Matthews correlation coefficient: 0.5


In [ ]:

from sklearn.metrics import classification_report
print(classification_report(y_test_binarized, predictions_binarized, target_names=['male'], labels=[1]))

              precision    recall  f1-score   support

        male       1.00      0.50      0.67         2

   micro avg       1.00      0.50      0.67         2
   macro avg       1.00      0.50      0.67         2
weighted avg       1.00      0.50      0.67         2

